
export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAIL: 'GET_CATEGORY_FAIL',
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAIL: 'CREATE_CATEGORY_FAIL',
}
export const productConstants = {
    GET_ALL_PRDUCTS_BY_SLUG_REQUEST: 'GET_ALL_PRDUCTS_BY_SLUG_REQUEST',
    GET_ALL_PRDUCTS_BY_SLUG_SUCCESS: 'GET_ALL_PRDUCTS_BY_SLUG_SUCCESS',
    GET_ALL_PRDUCTS_BY_SLUG_FAIL: 'GET_ALL_PRDUCTS_BY_SLUG_FAIL',

    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAIL: 'GET_PRODUCT_PAGE_FAIL',

    GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
    GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_FAIL: "GET_PRODUCT_BY_ID_FAIL"
}
export const authConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FAIL: "SIGNUP_FAIL",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",
    CLEAR_ERROR: "CLEAR_ERROR"
}

export const cartConstants = {
    GET_CART_ITEM_REQUEST: "GET_CART_ITEM_REQUEST",
    GET_CART_ITEM_SUCCESS: "GET_CART_ITEM_SUCCESS",
    GET_CART_ITEM_FAIL: "GET_CART_ITEM_FAIL",

    ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FAIL: 'ADD_TO_CART_FAIL',

    RESET_CART: 'RESET_CART',

    REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
    REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
    REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",

}

export const userConstants = {
    GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST",
    GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS",
    GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE",

    ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
    ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
    ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",

    ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
    ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
    ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

    GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
    GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
    GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

    GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
    GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
    GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",

}